# Generated by Django 2.2.12 on 2020-05-01 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('customer_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('employee_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('order_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
